# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 21:17
from __future__ import unicode_literals

import django.db.models.deletion
import evaluations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimators', '0001_initial'),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('_X_test_proxy', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='X_test', to='datasets.DataSet')),
                ('_estimator_proxy', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='estimators.Estimator')),
                ('_y_predicted_proxy', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='y_predicted', to='datasets.DataSet')),
                ('_y_test_proxy', models.ForeignKey(
                    blank=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='y_test', to='datasets.DataSet')),
            ],
            options={
                'db_table': 'evaluation_results',
            },
            bases=(evaluations.models.EvaluationMixin, models.Model),
        ),
    ]
