# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 21:17
from __future__ import unicode_literals

import estimators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimator',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('object_hash', models.CharField(default=None,
                                                 editable=False, max_length=64, unique=True)),
                ('object_file', models.FileField(blank=True, default=None,
                                                 editable=False, upload_to=estimators.get_upload_path)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'estimators',
            },
        ),
    ]
