# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=256)),
                ('object_hash', models.CharField(default=None, editable=False, max_length=64, unique=True)),
                ('object_file', models.FileField(
                    blank=True, default=None, editable=False, upload_to='estimators/')),
            ],
            options={
                'db_table': 'estimators',
            },
        ),
    ]
