# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import ml_model.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=256)),
                ('model_hash', models.CharField(default=ml_model.models.create_hash, max_length=64, unique=True)),
                ('s3_url', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
